import 'dart:convert';
import 'dart:io';

const String _configFileName = 'adk.json';

/// Development project metadata used by local ADK tooling.
class DevProjectConfig {
  /// Creates an immutable development project configuration.
  const DevProjectConfig({
    required this.appName,
    required this.agentName,
    required this.description,
    this.userId = 'user',
  });

  /// The logical application name used for session and runtime routing.
  final String appName;

  /// The root agent name shown in runtime events and UI.
  final String agentName;

  /// The human-readable description of the generated project.
  final String description;

  /// The default user id used by local dev flows.
  final String userId;

  /// A JSON-serializable representation of this configuration.
  Map<String, Object> toJson() {
    return <String, Object>{
      'appName': appName,
      'agentName': agentName,
      'description': description,
      'userId': userId,
    };
  }

  /// A copy of this config with selected fields replaced.
  DevProjectConfig copyWith({
    String? appName,
    String? agentName,
    String? description,
    String? userId,
  }) {
    return DevProjectConfig(
      appName: appName ?? this.appName,
      agentName: agentName ?? this.agentName,
      description: description ?? this.description,
      userId: userId ?? this.userId,
    );
  }
}

/// The normalized terminal folder name for [path].
///
/// Returns `my_agent` when [path] has no usable last segment.
String projectDirName(String path) {
  final String normalized = path.replaceAll('\\', '/');
  final String trimmed = normalized.endsWith('/')
      ? normalized.substring(0, normalized.length - 1)
      : normalized;
  final List<String> segments = trimmed.split('/');
  final String last = segments.isEmpty ? '' : segments.last.trim();
  if (last.isEmpty || last == '.') {
    return 'my_agent';
  }
  return last;
}

/// Loads [DevProjectConfig] from [projectDirPath].
///
/// Returns fallback metadata when `adk.json` is absent unless
/// [requireConfigFile] is true.
///
/// Throws a [FileSystemException] when [validateProjectDir] is true and
/// [projectDirPath] does not point to an existing directory.
/// Throws a [FormatException] when `adk.json` is not a JSON object.
Future<DevProjectConfig> loadDevProjectConfig(
  String projectDirPath, {
  bool validateProjectDir = false,
  bool requireConfigFile = false,
}) async {
  final Directory dir = Directory(projectDirPath);
  final File configFile = File(_joinPath(dir.path, _configFileName));
  final String fallbackName = projectDirName(projectDirPath);

  if (validateProjectDir) {
    final FileSystemEntityType entityType = await FileSystemEntity.type(
      dir.path,
    );
    if (entityType == FileSystemEntityType.notFound) {
      throw FileSystemException('Project directory does not exist.', dir.path);
    }
    if (entityType != FileSystemEntityType.directory) {
      throw FileSystemException('Project path is not a directory.', dir.path);
    }
  }

  if (!await configFile.exists()) {
    if (requireConfigFile) {
      throw FileSystemException(
        "Missing adk.json in project directory. Run 'adk create <dir>' first.",
        configFile.path,
      );
    }
    return DevProjectConfig(
      appName: fallbackName,
      agentName: 'root_agent',
      description: 'A development agent generated by adk_dart.',
    );
  }

  final String raw = await configFile.readAsString();
  final Object? decoded = jsonDecode(raw);
  if (decoded is! Map<String, dynamic>) {
    throw const FormatException('adk.json must contain a JSON object.');
  }

  String readString(String key, String fallback) {
    final Object? value = decoded[key];
    if (value is String && value.trim().isNotEmpty) {
      return value.trim();
    }
    return fallback;
  }

  return DevProjectConfig(
    appName: readString('appName', fallbackName),
    agentName: readString('agentName', 'root_agent'),
    description: readString(
      'description',
      'A development agent generated by adk_dart.',
    ),
    userId: readString('userId', 'user'),
  );
}

/// Creates a scaffolded ADK development project at [projectDirPath].
///
/// Generates `adk.json`, `.env`, `root_agent.yaml`, `agent.dart`, and
/// `README.md`.
///
/// Throws a [FileSystemException] when the target directory exists and is not
/// empty.
Future<void> createDevProject({
  required String projectDirPath,
  String? appName,
}) async {
  final Directory dir = Directory(projectDirPath);
  final String dirName = projectDirName(projectDirPath);
  final String resolvedAppName = _normalizeName(appName ?? dirName);
  final DevProjectConfig config = DevProjectConfig(
    appName: resolvedAppName,
    agentName: 'root_agent',
    description: 'Tells the current time in a specified city.',
  );

  if (await dir.exists()) {
    final bool hasEntries = !(await dir.list().isEmpty);
    if (hasEntries) {
      throw FileSystemException(
        'Project directory already exists and is not empty.',
        dir.path,
      );
    }
  } else {
    await dir.create(recursive: true);
  }

  await File(
    _joinPath(dir.path, _configFileName),
  ).writeAsString(const JsonEncoder.withIndent('  ').convert(config.toJson()));
  await File(
    _joinPath(dir.path, '.env'),
  ).writeAsString('GOOGLE_API_KEY="YOUR_API_KEY"\n');
  await File(
    _joinPath(dir.path, 'root_agent.yaml'),
  ).writeAsString(_rootAgentConfigTemplate());
  await File(_joinPath(dir.path, 'agent.dart')).writeAsString(_agentTemplate());
  await File(
    _joinPath(dir.path, 'README.md'),
  ).writeAsString(_projectReadmeTemplate(projectName: dirName));
}

String _normalizeName(String raw) {
  final String lower = raw.toLowerCase();
  final String sanitized = lower.replaceAll(RegExp(r'[^a-z0-9_]+'), '_');
  final String collapsed = sanitized.replaceAll(RegExp(r'_+'), '_');
  final String trimmed = collapsed.replaceAll(RegExp(r'^_+|_+$'), '');
  return trimmed.isEmpty ? 'my_agent' : trimmed;
}

String _joinPath(String left, String right) {
  if (left.endsWith(Platform.pathSeparator)) {
    return '$left$right';
  }
  return '$left${Platform.pathSeparator}$right';
}

String _agentTemplate() {
  return '''
import 'package:adk_dart/adk_dart.dart';

class EchoModel extends BaseLlm {
  EchoModel() : super(model: 'echo');

  @override
  Stream<LlmResponse> generateContent(
    LlmRequest request, {
    bool stream = false,
  }) async* {
    yield LlmResponse(content: Content.modelText('Agent template is ready.'));
  }
}

final Agent rootAgent = Agent(
  name: 'root_agent',
  model: EchoModel(),
);

Future<void> main() async {
  print('Generated template. Use `adk run .` or `adk web --port 8000 .`.');
}
''';
}

String _rootAgentConfigTemplate() {
  return '''
# yaml-language-server: \$schema=https://raw.githubusercontent.com/google/adk-python/refs/heads/main/src/google/adk/agents/config_schemas/AgentConfig.json
name: root_agent
description: A helpful assistant for user questions.
instruction: Answer user questions to the best of your knowledge
model: gemini-2.5-flash
''';
}

String _projectReadmeTemplate({required String projectName}) {
  return '''
# $projectName

This project was generated by `adk create`.

## Files

- `adk.json`: project metadata consumed by `adk run` and `adk web`.
- `root_agent.yaml`: root agent config loaded by CLI.
- `agent.dart`: starter template file you can customize.
- `.env`: environment variable placeholder.

## Commands

```bash
adk run .
adk web --port 8000 .
```
''';
}
