/// Compatibility planner models and heuristic planning implementation.
library;

/// Legacy utility planner retained for compatibility with early adk_dart APIs.
///
/// For Python parity planners, use `BuiltInPlanner` or `PlanReActPlanner`.
class PlanningRequest {
  /// Creates a rule-based planning request.
  PlanningRequest({required this.goal, List<String>? context})
    : context = context ?? <String>[];

  /// User goal to satisfy.
  final String goal;

  /// Optional context strings to incorporate into plan steps.
  final List<String> context;
}

/// One human-readable planning step.
class PlanningStep {
  /// Creates a planning step.
  PlanningStep({required this.title, this.reason});

  /// Short action title.
  final String title;

  /// Optional rationale for the step.
  final String? reason;
}

/// Result of [RuleBasedPlanner.plan].
class PlanningResult {
  /// Creates a planning result.
  PlanningResult({List<PlanningStep>? steps})
    : steps = steps ?? <PlanningStep>[];

  /// Ordered steps generated by the planner.
  final List<PlanningStep> steps;
}

/// Generates a fixed heuristic plan from a high-level request.
class RuleBasedPlanner {
  /// Builds a deterministic plan for [request].
  PlanningResult plan(PlanningRequest request) {
    final List<PlanningStep> steps = <PlanningStep>[
      PlanningStep(title: 'Understand goal', reason: request.goal),
      PlanningStep(
        title: 'Collect required context',
        reason: 'Gather data needed before execution.',
      ),
      PlanningStep(
        title: 'Execute and verify',
        reason: 'Run tasks and validate outputs.',
      ),
    ];

    if (request.context.isNotEmpty) {
      steps.insert(
        1,
        PlanningStep(
          title: 'Process provided context',
          reason: request.context.join('; '),
        ),
      );
    }

    return PlanningResult(steps: steps);
  }
}
