/// Model representing token consumption metrics and latency.
class AdkTokenUsage {
  /// Creates an [AdkTokenUsage].
  const AdkTokenUsage({
    this.promptTokens = 0,
    this.completionTokens = 0,
    this.totalTokens = 0,
    this.thoughtTokens = 0,
    this.latencyMs,
  });

  /// Tokens consumed by the prompt/input turn.
  final int promptTokens;

  /// Tokens generated by the model response.
  final int completionTokens;

  /// Total tokens consumed in the turn (prompt + completion).
  final int totalTokens;

  /// Reasoning/thought tokens if supported by the model (e.g. Gemini 2.0/3.7, Claude 3.7).
  final int thoughtTokens;

  /// Total generation latency in milliseconds.
  final int? latencyMs;

  /// Formatted total token string (e.g., "1.2k" or "850").
  String get formattedTotal {
    if (totalTokens >= 1000) {
      return '${(totalTokens / 1000).toStringAsFixed(1)}k';
    }
    return totalTokens.toString();
  }

  /// Copies this [AdkTokenUsage] with updated values.
  AdkTokenUsage copyWith({
    int? promptTokens,
    int? completionTokens,
    int? totalTokens,
    int? thoughtTokens,
    int? latencyMs,
  }) {
    return AdkTokenUsage(
      promptTokens: promptTokens ?? this.promptTokens,
      completionTokens: completionTokens ?? this.completionTokens,
      totalTokens: totalTokens ?? this.totalTokens,
      thoughtTokens: thoughtTokens ?? this.thoughtTokens,
      latencyMs: latencyMs ?? this.latencyMs,
    );
  }
}
