import 'package:flutter/foundation.dart';
import 'adk_attachment_model.dart';

/// The sender role of a chat message.
enum AdkMessageRole {
  /// Message sent by the human user.
  user,

  /// Message generated by the AI agent/model.
  model,

  /// Message representing a tool/function call or result.
  tool,

  /// System or error notification.
  system,
}

/// Code execution snippet and terminal output attached to a chat message.
///
/// ```dart
/// const execution = AdkCodeExecution(
///   language: 'PYTHON',
///   code: 'print(2 + 2)',
///   output: '4\n',
///   outcome: 'OUTCOME_OK',
/// );
/// ```
@immutable
class AdkCodeExecution {
  /// Creates an [AdkCodeExecution] payload.
  const AdkCodeExecution({
    this.language = 'PYTHON',
    this.code = '',
    this.output,
    this.outcome,
  });

  /// Programming language identifier (for example `'PYTHON'`).
  final String language;

  /// Source code executed by the agent.
  final String code;

  /// Standard output or error text produced by the execution, if available.
  final String? output;

  /// Execution outcome status (for example `'OUTCOME_OK'` or `'OUTCOME_FAILED'`).
  final String? outcome;

  /// Whether the code execution completed without a failure outcome.
  bool get isSuccess =>
      outcome == null ||
      outcome!.isEmpty ||
      outcome!.toUpperCase().contains('OK') ||
      outcome!.toUpperCase() == 'SUCCESS';

  /// Returns a copy of this [AdkCodeExecution] with updated fields.
  AdkCodeExecution copyWith({
    String? language,
    String? code,
    String? output,
    String? outcome,
  }) {
    return AdkCodeExecution(
      language: language ?? this.language,
      code: code ?? this.code,
      output: output ?? this.output,
      outcome: outcome ?? this.outcome,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AdkCodeExecution &&
        other.language == language &&
        other.code == code &&
        other.output == output &&
        other.outcome == outcome;
  }

  @override
  int get hashCode => Object.hash(language, code, output, outcome);
}

/// A single grounding citation source attached to a model response.
///
/// ```dart
/// const source = AdkGroundingSource(
///   title: 'ADK Documentation',
///   uri: 'https://google.github.io/adk-docs/',
/// );
/// ```
@immutable
class AdkGroundingSource {
  /// Creates an [AdkGroundingSource].
  const AdkGroundingSource({
    required this.title,
    required this.uri,
  });

  /// Display title of the cited source or domain.
  final String title;

  /// Target URI of the cited web page or document.
  final String uri;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AdkGroundingSource &&
        other.title == title &&
        other.uri == uri;
  }

  @override
  int get hashCode => Object.hash(title, uri);
}

/// Search queries and citation sources from model grounding metadata.
///
/// ```dart
/// const grounding = AdkGroundingInfo(
///   searchQueries: ['dart adk agents'],
///   sources: [
///     AdkGroundingSource(
///       title: 'ADK Docs',
///       uri: 'https://google.github.io/adk-docs/',
///     ),
///   ],
/// );
/// ```
@immutable
class AdkGroundingInfo {
  /// Creates an [AdkGroundingInfo].
  const AdkGroundingInfo({
    this.searchQueries = const <String>[],
    this.sources = const <AdkGroundingSource>[],
  });

  /// Search queries issued by the model during grounding.
  final List<String> searchQueries;

  /// Grounded web or document sources cited by the response.
  final List<AdkGroundingSource> sources;

  /// Whether there is no grounding query or source data.
  bool get isEmpty => searchQueries.isEmpty && sources.isEmpty;

  /// Whether at least one search query or citation source is present.
  bool get isNotEmpty => !isEmpty;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AdkGroundingInfo &&
        listEquals(other.searchQueries, searchQueries) &&
        listEquals(other.sources, sources);
  }

  @override
  int get hashCode => Object.hash(
        Object.hashAll(searchQueries),
        Object.hashAll(sources),
      );
}

/// A structured chat message displayed in the ADK Flutter chat UI.
@immutable
class AdkChatMessage {
  /// Creates an [AdkChatMessage].
  AdkChatMessage({
    required this.id,
    required this.role,
    required this.text,
    this.author = '',
    this.isPartial = false,
    this.thought,
    this.toolName,
    this.toolArgs,
    this.toolResult,
    this.codeExecution,
    this.grounding,
    this.isCompaction = false,
    this.errorMessage,
    this.attachments = const <AdkAttachment>[],
    this.metadata = const <String, dynamic>{},
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  /// Creates a user message.
  factory AdkChatMessage.user({
    required String id,
    required String text,
    String author = 'User',
    List<AdkAttachment> attachments = const <AdkAttachment>[],
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: .user,
      text: text,
      author: author,
      attachments: attachments,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Creates a model message.
  factory AdkChatMessage.model({
    required String id,
    required String text,
    String author = 'Agent',
    bool isPartial = false,
    String? thought,
    AdkCodeExecution? codeExecution,
    AdkGroundingInfo? grounding,
    bool isCompaction = false,
    List<AdkAttachment> attachments = const <AdkAttachment>[],
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: .model,
      text: text,
      author: author,
      isPartial: isPartial,
      thought: thought,
      codeExecution: codeExecution,
      grounding: grounding,
      isCompaction: isCompaction,
      attachments: attachments,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Creates a tool message.
  factory AdkChatMessage.tool({
    required String id,
    required String toolName,
    Map<String, dynamic>? toolArgs,
    dynamic toolResult,
    String text = '',
    String author = 'Tool',
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: .tool,
      text: text,
      author: author,
      toolName: toolName,
      toolArgs: toolArgs,
      toolResult: toolResult,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Creates an error or system message.
  factory AdkChatMessage.system({
    required String id,
    required String text,
    String? errorMessage,
    bool isCompaction = false,
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: .system,
      text: text,
      errorMessage: errorMessage,
      isCompaction: isCompaction,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Unique message identifier.
  final String id;

  /// Role of the message sender.
  final AdkMessageRole role;

  /// Text content of the message.
  final String text;

  /// Author name displayed on the message header.
  final String author;

  /// Whether this message is currently being streamed.
  final bool isPartial;

  /// Reasoning / thought process if supported.
  final String? thought;

  /// Name of the tool invoked, if any.
  final String? toolName;

  /// Arguments passed to the tool, if any.
  final Map<String, dynamic>? toolArgs;

  /// Alias for [toolArgs].
  Map<String, dynamic>? get toolArguments => toolArgs;

  /// Result returned by the tool, if any.
  final dynamic toolResult;

  /// Code execution snippet and output, if any.
  final AdkCodeExecution? codeExecution;

  /// Search grounding queries and citation sources, if any.
  final AdkGroundingInfo? grounding;

  /// Whether this message represents a compacted conversation summary.
  final bool isCompaction;

  /// Error message, if an error occurred.
  final String? errorMessage;

  /// Attached media or document files.
  final List<AdkAttachment> attachments;

  /// Custom metadata map.
  final Map<String, dynamic> metadata;

  /// Message creation timestamp.
  final DateTime timestamp;

  /// Whether this message was sent by the user.
  bool get isUser => role == .user;

  /// Whether this message was generated by the model/agent.
  bool get isModel => role == .model;

  /// Whether this message represents a tool/function call or result.
  bool get isTool => role == .tool;

  /// Whether this message is a system or error notification.
  bool get isSystem => role == .system;

  /// Whether this message is currently streaming.
  bool get isStreaming => isPartial;

  /// Whether this message represents an error.
  bool get isError => errorMessage != null || role == .system && errorMessage != null;

  /// Returns a copy of this message with updated fields.
  AdkChatMessage copyWith({
    String? id,
    AdkMessageRole? role,
    String? text,
    String? author,
    bool? isPartial,
    bool? isStreaming,
    bool? isError,
    String? thought,
    String? toolName,
    Map<String, dynamic>? toolArgs,
    Map<String, dynamic>? toolArguments,
    dynamic toolResult,
    AdkCodeExecution? codeExecution,
    AdkGroundingInfo? grounding,
    bool? isCompaction,
    String? errorMessage,
    List<AdkAttachment>? attachments,
    Map<String, dynamic>? metadata,
    DateTime? timestamp,
  }) {
    return AdkChatMessage(
      id: id ?? this.id,
      role: role ?? this.role,
      text: text ?? this.text,
      author: author ?? this.author,
      isPartial: isStreaming ?? isPartial ?? this.isPartial,
      thought: thought ?? this.thought,
      toolName: toolName ?? this.toolName,
      toolArgs: toolArguments ?? toolArgs ?? this.toolArgs,
      toolResult: toolResult ?? this.toolResult,
      codeExecution: codeExecution ?? this.codeExecution,
      grounding: grounding ?? this.grounding,
      isCompaction: isCompaction ?? this.isCompaction,
      errorMessage: errorMessage ?? this.errorMessage,
      attachments: attachments ?? this.attachments,
      metadata: metadata ?? this.metadata,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AdkChatMessage &&
        other.id == id &&
        other.role == role &&
        other.text == text &&
        other.isPartial == isPartial &&
        other.toolName == toolName &&
        other.codeExecution == codeExecution &&
        other.grounding == grounding &&
        other.isCompaction == isCompaction &&
        other.errorMessage == errorMessage &&
        listEquals(other.attachments, attachments);
  }

  @override
  int get hashCode => Object.hash(
        id,
        role,
        text,
        isPartial,
        toolName,
        codeExecution,
        grounding,
        isCompaction,
        errorMessage,
        Object.hashAll(attachments),
      );
}
