import 'package:flutter/foundation.dart';

/// The sender role of a chat message.
enum AdkMessageRole {
  /// Message sent by the human user.
  user,

  /// Message generated by the AI agent/model.
  model,

  /// Message representing a tool/function call or result.
  tool,

  /// System or error notification.
  system,
}

/// A structured chat message displayed in the ADK Flutter chat UI.
@immutable
class AdkChatMessage {
  /// Creates an [AdkChatMessage].
  AdkChatMessage({
    required this.id,
    required this.role,
    required this.text,
    this.author = '',
    this.isPartial = false,
    this.thought,
    this.toolName,
    this.toolArgs,
    this.toolResult,
    this.errorMessage,
    this.metadata = const <String, dynamic>{},
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  /// Creates a user message.
  factory AdkChatMessage.user({
    required String id,
    required String text,
    String author = 'User',
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: AdkMessageRole.user,
      text: text,
      author: author,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Creates a model message.
  factory AdkChatMessage.model({
    required String id,
    required String text,
    String author = 'Agent',
    bool isPartial = false,
    String? thought,
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: AdkMessageRole.model,
      text: text,
      author: author,
      isPartial: isPartial,
      thought: thought,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Creates a tool message.
  factory AdkChatMessage.tool({
    required String id,
    required String toolName,
    Map<String, dynamic>? toolArgs,
    dynamic toolResult,
    String text = '',
    String author = 'Tool',
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: AdkMessageRole.tool,
      text: text,
      author: author,
      toolName: toolName,
      toolArgs: toolArgs,
      toolResult: toolResult,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Creates an error or system message.
  factory AdkChatMessage.system({
    required String id,
    required String text,
    String? errorMessage,
    DateTime? timestamp,
    Map<String, dynamic> metadata = const <String, dynamic>{},
  }) {
    return AdkChatMessage(
      id: id,
      role: AdkMessageRole.system,
      text: text,
      errorMessage: errorMessage,
      timestamp: timestamp,
      metadata: metadata,
    );
  }

  /// Unique message identifier.
  final String id;

  /// Role of the message sender.
  final AdkMessageRole role;

  /// Text content of the message.
  final String text;

  /// Author name displayed on the message header.
  final String author;

  /// Whether this message is currently being streamed.
  final bool isPartial;

  /// Reasoning / thought process if supported.
  final String? thought;

  /// Name of the tool invoked, if any.
  final String? toolName;

  /// Arguments passed to the tool, if any.
  final Map<String, dynamic>? toolArgs;

  /// Alias for [toolArgs].
  Map<String, dynamic>? get toolArguments => toolArgs;

  /// Result returned by the tool, if any.
  final dynamic toolResult;

  /// Error message, if an error occurred.
  final String? errorMessage;

  /// Custom metadata map.
  final Map<String, dynamic> metadata;

  /// Message creation timestamp.
  final DateTime timestamp;

  /// Whether this message was sent by the user.
  bool get isUser => role == AdkMessageRole.user;

  /// Whether this message was generated by the model/agent.
  bool get isModel => role == AdkMessageRole.model;

  /// Whether this message represents a tool/function call or result.
  bool get isTool => role == AdkMessageRole.tool;

  /// Whether this message is a system or error notification.
  bool get isSystem => role == AdkMessageRole.system;

  /// Whether this message is currently streaming.
  bool get isStreaming => isPartial;

  /// Whether this message represents an error.
  bool get isError => errorMessage != null || role == AdkMessageRole.system && errorMessage != null;

  /// Returns a copy of this message with updated fields.
  AdkChatMessage copyWith({
    String? id,
    AdkMessageRole? role,
    String? text,
    String? author,
    bool? isPartial,
    bool? isStreaming,
    bool? isError,
    String? thought,
    String? toolName,
    Map<String, dynamic>? toolArgs,
    Map<String, dynamic>? toolArguments,
    dynamic toolResult,
    String? errorMessage,
    Map<String, dynamic>? metadata,
    DateTime? timestamp,
  }) {
    return AdkChatMessage(
      id: id ?? this.id,
      role: role ?? this.role,
      text: text ?? this.text,
      author: author ?? this.author,
      isPartial: isStreaming ?? isPartial ?? this.isPartial,
      thought: thought ?? this.thought,
      toolName: toolName ?? this.toolName,
      toolArgs: toolArguments ?? toolArgs ?? this.toolArgs,
      toolResult: toolResult ?? this.toolResult,
      errorMessage: errorMessage ?? this.errorMessage,
      metadata: metadata ?? this.metadata,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AdkChatMessage &&
        other.id == id &&
        other.role == role &&
        other.text == text &&
        other.isPartial == isPartial &&
        other.toolName == toolName &&
        other.errorMessage == errorMessage;
  }

  @override
  int get hashCode =>
      Object.hash(id, role, text, isPartial, toolName, errorMessage);
}
